### ISSUE TITLE
小白的一些疑问

### ISSUE THREAD

**Issue by Berryberg** [weijiew/codestep#25]
关于cs61a:
请问vscode使用wsl的bash做为终端后，路径总是出现问题怎么办呢？因为路径总是有问题 所以用不了ok文件 如果我在windows下的路径是D:\cs61a\lab00 我该输入什么来进入到这条路径下呢 麻烦大神指教（新手小白）

**Comment by weijiew** [comment]
需要加 mnt 的前缀，按照 linux 的路径形式去访问

> cd /mnt/d/cs61a/lab00

在 /mnt 路径下可以看到 win 下的盘符。

**Comment by Berryberg** [comment]
谢谢大佬指教 🙂
