### ISSUE TITLE
关于博客搭建

### ISSUE THREAD

**Issue by echoxxzhang** [weijiew/codestep#34]
大佬你好，如何搭建这样的博客呢？我很喜欢这样的架构。

**Comment by weijiew** [comment]
抱歉哈，最近没怎么看邮箱。


页面是用&nbsp;&nbsp;VuePress (vuejs.org)&nbsp;搭建的。然后换个主题就行。这个主题我是抄别人的，原版好像已经改版了，你可以多挑挑选择一个自己喜欢的。改主题比较费时间。


我加过一个 CS144 的交流群，485077457 但是没怎么用。做那门课的时候卡在了某个细节上不知道是网络的原因还是我电脑的原因所以暂停了，后续我会捡起来的。最近实在是太忙了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weijiew/codestep"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月19日(星期三) 凌晨0:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[weijiew/codestep] 关于博客搭建 (#34)





 
大佬你好，如何搭建这样的博客呢？我很喜欢这样的架构。
